<a href="https://colab.research.google.com/github/shahpranshu27/HandsOn_ML/blob/main/Diabetes_Prediction_kNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset taken from https://www.kaggle.com/datasets/akshaydattatraykhare/diabetes-dataset

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

There are some columns in which, we can't have 0s. So, we will replace those with mean.

In [3]:
zeroes_not_accepted = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI', 'Insulin']

for column in zeroes_not_accepted:
  df[column] = df[column].replace(0, np.NaN)
  mean = int(df[column].mean(skipna=True))
  df[column] = df[column].replace(np.NaN, mean)

  # Alternative solution
  # mean = int(df[column].mean(skipna=True))
  # df[column] = df[column].replace(0, mean)

In [4]:
# split dataset
X = df.iloc[:, 0:8]
Y = df.iloc[:, 8]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

Any algorithm that computes distance or assumes normality, always scale your features.

In [5]:
# feature scaling
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [6]:
classifier = KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')

In [7]:
classifier.fit(X_train, Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [8]:
Y_pred = classifier.predict(X_test)
Y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
cm = confusion_matrix(Y_test, Y_pred)
cm

array([[94, 13],
       [15, 32]])

In [10]:
f1_score(Y_test, Y_pred)

0.6956521739130436

In [11]:
accuracy_score(Y_test, Y_pred)

0.8181818181818182

In [12]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [13]:
sample_input = {
    'Pregnancies': 0,
    'Glucose': 80,
    'BloodPressure': 90,
    'SkinThickness': 30,
    'Insulin': 0,
    'BMI': 33.7,
    'DiabetesPedigreeFunction': 0.627,
    'Age':21
}

In [14]:
sample_input = pd.DataFrame(sample_input, index=[0])
sample_input

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            0       80             90             30        0  33.7   

   DiabetesPedigreeFunction  Age  
0                     0.627   21

In [15]:
classifier.predict(sample_input)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


array([1])