<a href="https://colab.research.google.com/github/shahpranshu27/HandsOn_ML/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ways to initialize nparray

* np.ones()

* np.zeros()

* np.random()

In [1]:
import numpy as np

In [2]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.random.random((3,4))

array([[0.65099518, 0.32966867, 0.44963528, 0.45753371],
       [0.79280766, 0.80526092, 0.32667427, 0.88878741],
       [0.72669192, 0.82894992, 0.40760934, 0.24697324]])

In [5]:
np.linspace(0,10,5) # (lower bound, upper bound, number of items you want to generate)
# what linspace or linearly space does is that, it takes lower and upper range, and divides 'n' numbers in linear way

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.identity(3) # matrix of nxn, where diagonal elemts are 1, others are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# int32 takes 4 bytes
# int64 takes 8 bytes, similar to float

In [8]:
# Scalar Operations

In [9]:
# arithmetic
a1 = np.arange(12)
a2 = np.arange(12, 24)

In [10]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
a2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [12]:
print(a1 * 2)
print(a1 - 5)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[-5 -4 -3 -2 -1  0  1  2  3  4  5  6]


In [13]:
# relational

a1 > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [14]:
a2 > 9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [15]:
a2 == 15

array([False, False, False,  True, False, False, False, False, False,
       False, False, False])

In [16]:
# vector operations

In [17]:
a1 + a2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])

Important Array Functions:
* min/max/prod/sum

* round/floor/ceil

* mean/median/standard deviation/variance/trigonometry

* arrays dot product

* log and exponents


Indexing and Slicing

In [18]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [19]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [20]:
a2[0,:] # first row, all columns

array([0, 1, 2, 3])

In [21]:
a2[:,3] # all rows, fourth column

array([ 3,  7, 11])

In [22]:
a2[1:3,1:3] # second and third row, second and third column

array([[ 5,  6],
       [ 9, 10]])

In [23]:
a2[0::2, 0::3]

array([[ 0,  3],
       [ 8, 11]])

In [24]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [25]:
a2[1, ::3]

array([4, 7])

In [26]:
# Transpose -> rows gets converted to columns, and cols get converted to rows
# ravel -> it converts array of any dimensions to 1D array

Stacking

* Horizontal stacking

* Vertical stacking

In [27]:
# hstack
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [28]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [31]:
# vstack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

* Horizontal split

* Vertical split

In [32]:
# hsplit
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [33]:
# vsplit
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]