<a href="https://colab.research.google.com/github/shahpranshu27/HandsOn_ML/blob/main/SimpleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset:
https://raw.githubusercontent.com/ybifoundation/Dataset/main/Salary%20Data.csv

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/ybifoundation/Dataset/main/Salary%20Data.csv')
df

Experience Years  Salary
0                1.1   39343
1                1.2   42774
2                1.3   46205
3                1.5   37731
4                2.0   43525
5                2.2   39891
6                2.5   48266
7                2.9   56642
8                3.0   60150
9                3.2   54445
10               3.2   64445
11               3.5   60000
12               3.7   57189
13               3.8   60200
14               3.9   63218
15               4.0   55794
16               4.0   56957
17               4.1   57081
18               4.3   59095
19               4.5   61111
20               4.7   64500
21               4.9   67938
22               5.1   66029
23               5.3   83088
24               5.5   82200
25               5.9   81363
26               6.0   93940
27               6.2   91000
28               6.5   90000
29               6.8   91738
30               7.1   98273
31               7.9  101302
32               8.2  113812
33               8.5  111620
34               8.7  109431
35               9.0  105582
36               9.5  116969
37               9.6  112635
38              10.3  122391
39              10.5  121872

In [3]:
df.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [4]:
x = df[['Experience Years']]

In [5]:
Y = df[['Salary']]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, Y, train_size=0.7, random_state=2529)

In [7]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((28, 1), (12, 1), (28, 1), (12, 1))

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [9]:
model.fit(X_train, Y_train)

LinearRegression()

In [10]:
model.coef_

array([[9405.61663234]])

In [11]:
model.intercept_

array([26596.96131107])

In [12]:
model.predict(X_test)

array([[ 90555.15441095],
       [ 59516.61952424],
       [106544.70268592],
       [ 64219.42784041],
       [ 68922.23615658],
       [123474.81262412],
       [ 84911.78443155],
       [ 63278.86617718],
       [ 65159.98950364],
       [ 61397.74285071],
       [ 37883.70126987],
       [ 50111.00289191]])

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error

In [15]:
mean_absolute_error(Y_test, model.predict(X_test))

4005.9263101681768

In [16]:
mean_absolute_percentage_error(Y_test, model.predict(X_test))

0.06384602996141632

In [18]:
mean_squared_error(Y_test, model.predict(X_test))

24141421.671440993